export const ROUTES_PATH = {
  intro: '/',
  home: '/home',
  mypage: '/mypage',
  signin: '/signin',
  signup: '/signup',
  findAccount: '/findAccount',
  signupSuccess: '/signupSuccess',
  userInfo: '/userInfo',
  profile: '/profile',
  track: '/track',
  education: '/education',
  experience: '/experience',
  keyword: '/keyword',
  loading: '/loading',
  customizedCareer: '/customizedCareer',
  chat: '/chat',
  bookmark: '/bookmark',
} as const;
